usr/share/doc/gnutls/*.html usr/share/doc/gnutls-doc/html
usr/share/doc/gnutls/*.png usr/share/doc/gnutls-doc/html
usr/share/gtk-doc/html/gnutls/*.css usr/share/doc/gnutls-doc/api-reference
usr/share/gtk-doc/html/gnutls/*.devhelp* usr/share/doc/gnutls-doc/api-reference
usr/share/gtk-doc/html/gnutls/*html usr/share/doc/gnutls-doc/api-reference
usr/share/gtk-doc/html/gnutls/*png usr/share/doc/gnutls-doc/api-reference
